name: Lint & Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.3'

      - name: Setup Go environment
        run: |
          go mod download
          go get -t .

      - name: Linting
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true

      - name: Unit tests
        run: |
          go test ./... -coverprofile coverage.out -covermode atomic
          go tool cover -func coverage.out
