name: Coverage

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.3'

      - name: Setup Go environment
        run: |
          go mod download
          go get -t .

      - name: Unit tests
        run: |
          go test ./... -race -coverprofile coverage.out -covermode count
          go tool cover -func coverage.out
